//! Minimal ldk-node wrapper for smite fuzzing.
//!
//! Uses bitcoind RPC as the backend, prints the node's pubkey on startup, and
//! waits for SIGTERM to shut down cleanly. Ignores all events generated by
//! ldk-node since we reset the VM after each fuzz iteration anyway.

use std::net::SocketAddr;
use std::time::Duration;

use ldk_node::Builder;
use ldk_node::bitcoin::Network;

/// Path prefix the crash handler reads panic reports from.
const PANIC_LOG_PATH: &str = "/tmp/smite-panic.log";

/// Stores the panic message where the `LD_PRELOADed` crash handler can retrieve
/// it. With `panic = "abort"`, panics only reach stderr, which scenario/Nyx
/// discards, so this allows crash reports to include the panic message and its
/// source location.
fn install_panic_hook() {
    let path = format!("{PANIC_LOG_PATH}.{}", std::process::id());
    let default_hook = std::panic::take_hook();

    std::panic::set_hook(Box::new(move |info| {
        // Renders as "panicked at <file>:<line>:<col>:\n<message>".
        let _ = std::fs::write(&path, format!("{info}\n"));
        default_hook(info);
    }));
}

/// Blocks SIGUSR1, SIGTERM, and SIGINT so they can be synchronously handled
/// with `sigwait()`.
///
/// Blocking supersedes the disposition inherited across exec, which for SIGUSR1
/// defaults to terminating the process. That distinction is the whole point: an
/// *ignored* signal is discarded the moment it is delivered, while a *blocked*
/// one stays pending until `sigwait()` consumes it, regardless of its
/// disposition. So this call is what makes target's SIGUSR1 observable, and
/// why nothing here calls `sigaction`: the wait loop below is the only consumer
/// these signals need.
///
/// Standard signals do not queue, so a burst of SIGUSR1 collapses into one
/// pending instance and thus one wakeup. That is fine here: each wakeup syncs
/// the wallet against bitcoind's current tip, not against a single block.
fn setup_signal_set() -> libc::sigset_t {
    // SAFETY: `set` is zeroed and then initialized by `sigemptyset` before any
    // read; every call receives a valid pointer to it. The null `oldset` is
    // explicitly allowed by `pthread_sigmask`, which discards the previous mask.
    unsafe {
        let mut set: libc::sigset_t = std::mem::zeroed();

        libc::sigemptyset(&raw mut set);
        libc::sigaddset(&raw mut set, libc::SIGUSR1);
        libc::sigaddset(&raw mut set, libc::SIGTERM);
        libc::sigaddset(&raw mut set, libc::SIGINT);

        let ret = libc::pthread_sigmask(libc::SIG_BLOCK, &raw const set, std::ptr::null_mut());
        assert_eq!(ret, 0, "failed to block signals");

        set
    }
}

fn main() {
    install_panic_hook();

    // The target sends SIGUSR1 to request an immediate chain sync.
    // SIGTERM/SIGINT are used for graceful shutdown.
    let signal_set = setup_signal_set();

    let args: Vec<String> = std::env::args().collect();
    if args.len() != 5 {
        eprintln!(
            "Usage: {} <data-dir> <listen-port> <bitcoind-rpc-port> <target-blockheight>",
            args[0]
        );
        std::process::exit(1);
    }

    let data_dir = args[1].clone();
    let listen_port: u16 = args[2].parse().expect("valid listen port");
    let rpc_port: u16 = args[3].parse().expect("valid RPC port");
    let target_blockheight: u32 = args[4].parse().expect("valid target blockheight");

    let listen_addr: SocketAddr = format!("0.0.0.0:{listen_port}")
        .parse()
        .expect("valid listen address");

    let node = Builder::new()
        .set_network(Network::Regtest)
        .set_chain_source_bitcoind_rpc(
            "127.0.0.1".to_string(),
            rpc_port,
            "rpcuser".to_string(),
            "rpcpass".to_string(),
        )
        .set_listening_addresses(vec![listen_addr.into()])
        .expect("valid listening addresses")
        .set_storage_dir_path(data_dir)
        .build()
        .expect("node build");

    node.start().expect("node start");

    // Wait for the chain to sync to the target blockheight before signaling
    // readiness. ldk-node polls bitcoind every 2 seconds, so this can take a
    // few seconds after startup.
    while node.status().current_best_block.height < target_blockheight {
        std::thread::sleep(Duration::from_secs(1));
    }

    // Output for LdkTarget to parse.
    println!("PUBKEY:{}", node.node_id());
    println!("READY");

    // Wait for signals. sigwait() blocks here without polling and returns
    // immediately when the target sends SIGUSR1 or the process receives
    // SIGTERM/SIGINT.
    loop {
        let mut signal = 0;

        // SAFETY: both pointers refer to live locals, and `signal_set` was
        // initialized by `setup_signal_set` above.
        let ret = unsafe { libc::sigwait(&raw const signal_set, &raw mut signal) };
        assert_eq!(ret, 0, "sigwait failed: {ret}");

        match signal {
            libc::SIGUSR1 => {
                // Sync the wallet whenever the target asks for it.
                // ldk-node's own 2s background poll keeps running, so this is
                // technically redundant and may race it, but that's safe:
                // ldk-node coalesces concurrent syncs, so whichever loses the
                // race just waits on the in-flight sync's result rather than
                // applying the block twice. We accept the redundancy to sync on
                // demand instead of up to 2s later.
                if let Err(e) = node.sync_wallets() {
                    eprintln!("sync_wallets failed: {e}");
                }
            }
            libc::SIGTERM | libc::SIGINT => {
                break;
            }
            _ => unreachable!("received unexpected signal {signal}"),
        }
    }

    node.stop().expect("node stop");
}
